spring.application.name=conference-service
server.port=8082
spring.datasource.url=jdbc:h2:mem:conferences-db
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
spring.h2.console.enabled=true
