spring.application.name=keynote-service
server.port=8081
spring.datasource.url=jdbc:h2:mem:keynotes-db
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
spring.h2.console.enabled=true
